Http:
  host: "192.168.1.107"
  port: 8080
  endpoint: "/legit"
  sleep: 5
  userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/102.0"
  malPath:
    - "kitten/basicKitten/"
    - "kitten/bananaKitten/"
    - "kitten/dllKitten/"